version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: api-gateway
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth
      - user
      - search
      - cart
      - order
      - payment
      - product
      - wishlist
      - recommendation
      - notification
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - ecommerce-net

  search:
    build: ./search-service
    container_name: search-service
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__Elasticsearch=http://elasticsearch:9200
      - REDIS_CONNECTION=redis:6379
      - Kafka__BootstrapServers=kafka:9092
    ports:
      - "5001:5000"
    depends_on:
      elasticsearch:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - ecommerce-net

  cart:
    build: ./cart-service
    container_name: cart-service
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__Redis=redis:6379
      - Kafka__BootstrapServers=kafka:9092
    ports:
      - "5002:5000"
    depends_on:
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - ecommerce-net

  order:
    build: ./order-service
    container_name: order-service
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__Postgres=postgres:5432
      - Kafka__BootstrapServers=kafka:9092
    ports:
      - "5003:5000"
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - ecommerce-net

  payment:
    build: ./payment-service
    container_name: payment-service
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__Postgres=postgres:5432
    ports:
      - "5004:5000"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - ecommerce-net

  user:
    build: ./user-service
    container_name: user-service
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__MySQL=mysql:3306
    ports:
      - "5005:5000"
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - ecommerce-net

  auth:
    build: ./auth-service
    container_name: auth-service
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__Postgres=postgres:5432
    ports:
      - "5006:5000"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - ecommerce-net

  # Domain Services
  product:
    build: ./product-service
    container_name: product-service
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - MongoDbSettings__ConnectionString=mongodb://mongo:27017
      - MongoDbSettings__DatabaseName=ecommerce_db
      - MongoDbSettings__ProductCollectionName=products
      - Kafka__BootstrapServers=kafka:9092
    ports:
      - "5007:5000"
    depends_on:
      mongo:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      kafka:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - ecommerce-net

  wishlist:
    build: ./wishlist-service
    container_name: wishlist-service
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__Redis=redis:6379
    ports:
      - "5008:5000"
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - ecommerce-net

  recommendation:
    build: ./recommendation-service
    container_name: recommendation-service
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__Neo4j=neo4j://neo4j:7687
      - Kafka__BootstrapServers=kafka:9092
    ports:
      - "5009:5000"
    depends_on:
      neo4j:
        condition: service_healthy
      kafka:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - ecommerce-net

  notification:
    build: ./notification-service
    container_name: notification-service
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__MongoDB=mongodb://mongo:27017
      - Kafka__BootstrapServers=kafka:9092
    ports:
      - "5010:5000"
    depends_on:
      mongo:
        condition: service_healthy
      kafka:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - ecommerce-net

  # Core infrastructure
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - ecommerce-net

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    environment:
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 80s
    networks:
      - ecommerce-net

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    healthcheck:
      test: ["CMD", "zkServer.sh", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - ecommerce-net

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ecommerce
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - ecommerce-net

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - ecommerce-net

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=users
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - ecommerce-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - ecommerce-net

volumes:
  redis-data:
  pg-data:
  mysql-data:
  mongo-data:
  es-data:

networks:
  ecommerce-net:
    driver: bridge
